### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by wd0472** [act-framework/act#37]
12:56:00.284 [jobs-thread-1] WARN act.job.Job - error executing job register-singleton-instances
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at act.app.SingletonRegistry.doRegister(SingletonRegistry.java:76)
	at act.app.SingletonRegistry.access$000(SingletonRegistry.java:34)
	at act.app.SingletonRegistry$1.run(SingletonRegistry.java:50)
	at act.job.Job$3.apply(Job.java:349)
	at act.job.Job.doJob(Job.java:311)
	at act.job.Job.run(Job.java:250)
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:431)
	at act.job.Job.doJob(Job.java:311)
	at act.job.Job.run(Job.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
question;  JDK 1.7 Startup error
Solution：revise JDK 1.8

**Comment by joaomilho** [comment]
Wrong repo.
